name: Build TS Clients and Examples
on:
  repository_dispatch:
    types: [build_publish_ts]

jobs:
  generate:
    name: build TS clients and examples
    runs-on: ubuntu-latest
    steps:
      - name: Check m3o-js repo
        uses: actions/checkout@v3
        with:
          path: m3o-js

      - name: Check micro/services repo
        uses: actions/checkout@v3
        with:
          repository: 'micro/services'
          path: services

      - name: Check m3o/m3o repo
        uses: actions/checkout@v3
        with:
          repository: 'm3o/m3o'
          path: m3o

      - name: Generate m3o-js clients
        uses: GWT-M3O-TEST/m3o-generator-action@main
        with:
          target: 'ts'
          services_path: services

      - name: Adjust generated things before pushing
        working-directory: services
        
        run: |
          # sync the clients to m3o-js/
          rsync -avz clients/ts/ ../m3o-js/
          # sync the examples to m3o-js/examples
          rsync -avz examples/js/ ../m3o-js/examples/

      - name: install prettier
        working-directory: m3o-js
        run: |
          sudo npm install -g prettier

      - name: format m3o-js
        working-directory: m3o-js
        run:  prettier -w .

      - name: update version number
        working-directory: m3o-js
        run: |
          oldver=$(cat package.json | grep version | head -1) 
          patch=$(echo $oldver | awk -F. '{ print $3}' | sed 's/"//g')
          newpatch=$(($patch+1))\" 
          seg1=$(echo $oldver | awk -F. '{ print $1}') 
          seg2=$(echo $oldver | awk -F. '{ print $2}') 
          newver="$seg1.$seg2.$newpatch" 
          sed -i "s/$oldver/$newver/" package.json
          echo "old $oldver"
          echo "new $newver"
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          cwd: m3o-js
          message: Push to M3O-JS repo
          pathspec_error_handling: exitImmediately

      # - name: Set up Go 1.17
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.17
      #   id: go

      
